---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Create Collectd yumrepo file
  yum_repository:
    name: collectd
    description: Collectd YUM repo
    baseurl: "{{ collectd_yumrepo_url }}"
    gpgcheck: no
    params: "{{ collectd_yumrepo_params }}"
  tags:
    - collectd_pkg

- name: Install Collectd
  package:
    name: "{{ collectd_pkg }}"
    state: present
  notify:
    - Restart collectd service
  tags:
    - collectd_pkg

- name: Install additional Collectd plugins
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ collectd_pkg_plugins }}"
  notify:
    - Restart collectd service
  tags:
    - collectd_pkg

- name: Configure Collectd
  template:
    src: collectd.conf.j2
    dest: "{{ collectd_config_path }}"
  notify:
    - Restart collectd service
  tags:
    - collectd_config

- name: Configure custom types.db
  template:
    src: types.db.j2
    dest: "{{ collectd_global_options_default_typesdb_custom }}"
  when: >
    collectd_global_options_default_typesdb_custom and
    collectd_types
  notify:
    - Restart collectd service
  tags:
    - collectd_config

- name: Remove custom types.db file
  file:
    path: "{{ collectd_global_options_default_typesdb_custom }}"
    state: absent
  when: >
    collectd_global_options_default_typesdb_custom and
    not collectd_types
  notify:
    - Restart collectd service
  tags:
    - collectd_config

- name: Make sure collectd service is enabled
  service:
    name: collectd
    enabled: yes
  tags:
    - collectd_service

- name: Make sure collectd service is running
  service:
    name: collectd
    state: running
  register: collectd_service_started
  tags:
    - collectd_service
